[workspace]
members = [
    # "casper-shorts-charts",
        # "casper-shorts-client",
    "casper-shorts-contracts",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
